name: Comment

on: 
  issue_comment:
    types: [created, edited]
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Comment on issue #${{ github.event.issue.number }} ${{ github.event.issue.title }}"
          echo "User id ${{ github.event.issue.user.id }}"
          echo "Comment conent ${{ github.event.issue.comment.body }}"
          echo "Event id ${{ github.event.id }}"